#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/**
 * main - Entry point
 *
 * This program prints a random number and its last digit compared to 5
 * The random number is generated by rand function and assigned to n
 * printf function prints the the number and its lst digit and the coparison string
 *
 * Return: Always (0) (success)
 */

int main(void)
{
	int n, last_digit;

	srand(time(0));
	n = rand() - RAND_MAX / 2;
	
	/* My Code */
	last_digit = n % 10;
	if (last_digit > 5)
	{
		printf("Last digit of %i is %i and is greater than 5\n", n, last_digit);
	}
	else if (last_digit == 0)
	{
		printf("Last digit of %i is %i and is 0\n", n, last_digit);
	}
	else
	{
		printf("Last digit of %i is %i and is less than 6 and not 0\n", n, last_digit);
	}
	return (0);
}
